version: "3"
services:
    whatsapp-chatgpt:
        image: ghcr.io/askrella/whatsapp-chatgpt:master
        environment:
            OPENAI_API_KEY: "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"
            OPENAI_GPT_MODEL: ""
            PREFIX_ENABLED: ""
        volumes:
            - session-data:/app/session
volumes:
    session-data:
